version: "2"

run:
  timeout: 3m

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - intrange
    - misspell
    - modernize
    - nilerr
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
      enabled-checks:
        - boolExprSimplify
        - nilValReturn
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor

formatters:
  enable:
    - gofumpt
    - goimports

output:
  sort-order:
    - file
