# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: clotilde

before:
  hooks:
    - go mod tidy

builds:
  - id: clotilde
    main: ./main.go
    binary: clotilde
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/fgrehm/clotilde/cmd.version={{.Version}}
      - -X github.com/fgrehm/clotilde/cmd.commit={{.Commit}}
      - -X github.com/fgrehm/clotilde/cmd.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    ids:
      - clotilde

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: fgrehm
    name: clotilde
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
